services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
            tags:
                - rahulcodepython/personal-portfolio:latest

        container_name: portfolio

        ports:
            - "3000:3000"

        restart: always
